### ISSUE TITLE
Please remove Wrong import statement in npmjs

### ISSUE THREAD

**Issue by vadempur** [alhazmy13/angular-csv-ext#36] opened 2019-05-03 12:25 UTC
In npmjs import statement is wrong please replace with correct import statement

**Comment by h3xx** [comment] 2019-05-07 17:21
Evidently this broke when updating 0.2.10 -> 0.2.11.

Really, though, devs: a patch level bump should not break all existing import statements.

**Comment by argodeep** [comment] 2019-07-17 09:45
Use this for import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv';

**Comment by h3xx** [comment] 2019-07-18 03:49
Possible dupe of #29

**Comment by alhazmy13** [comment] 2019-08-13 20:11
Hi all, We fixed this in version [1.0.0](https://github.com/alhazmy13/angular-csv-ext/releases/tag/1.0.0)

Please note: The new name for this package is `angular-csv-ext`, so remove `angular5-csv` and install the new one.

Thanks

**Closed by alhazmy13** 2019-08-13 20:11 UTC
